namespace UnityEditor.PixyzPlugin4Unity.Toolbox
{
	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -20)]
		public static void Acf2aa16e_100a_47b4_a9e3_c80034c82efd() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -19)]
		public static void A071a7a61_e090_4bb0_9ce6_af484fa1597a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -18)]
		public static void A70f6e99c_b78f_488d_88f7_cccf4140e474() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -17)]
		public static void Ae57f1168_0f0a_4862_b92e_786e29620095() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -15)]
		public static void A244861cf_ee3f_41be_a9de_be6965b06e55() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -14)]
		public static void Ae53454f6_783f_401e_b71f_65cf027516dc() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -13)]
		public static void Aef0b1df3_ef1b_429c_ad3e_17ba451fdb06() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -12)]
		public static void Ac2e6a2e6_b4fb_4676_9bd3_1e41494dd490() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -12)]
		public static void Ad1f8d5f0_41fd_4e8b_bec8_4fc9b3333977() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -11)]
		public static void A70b54822_d035_4e12_88ea_0e1790d36096() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -10)]
		public static void Af0525828_b4d9_4b4e_b0d2_083b095a107d() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -9)]
		public static void A0100c8b9_50a4_47e5_9f24_20e11c21a768() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -8)]
		public static void Aceeee210_21da_44cb_95f3_6e06c25dec40() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -7)]
		public static void Abcc27532_1a9b_4894_bab4_be93367852a8() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -6)]
		public static void A250c0b20_7109_4d5b_9eb3_6413d6562b41() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -5)]
		public static void Aaf6f807d_1dee_4666_b47e_d17ba7690700() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -4)]
		public static void A8b09e901_4558_468d_8c40_463852c888fa() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -3)]
		public static void A897eb03d_354e_49e0_b655_57f59dd5070a() { Toolbox.RunToolboxAction(new UnityEditor.PixyzPlugin4Unity.Toolbox.CreateLightmapUVs()); }

	}
}